### ISSUE TITLE
Purpose of this library ?

### ISSUE THREAD

**Issue by zadlg** [Donerkebap13/DonerSerializer#1]
Hello,
I don't understand the purpose of this library ?

It requires the usage of plenty of macros (in c++..), and it's based on [rapidjson](https://github.com/Tencent/rapidjson). So why isn't it better to directly use rapidjson ?

**Comment by Donerkebap13** [comment]
For declaring the reflection data in compile-time, we need to use macros. It can be done without macros obviously but it'd make the library non attractive at all. THe ones used for serialize/deserialize is just to provide a more semantic API. There are plans of rethink the used macros and find smarter ways of doing things.

Why don't use rapidjson directly?

Well, DonerSerializer used rapidjson interanlly, and it abstracts the way a user would serialize an int, or a std::vector<std::map<int, std::vector<CustomClass>>>. Try to write serialization code for that or any other combination of types manually, in several different places through your code using rapidjson and then try to do it using DonerSerializer.
DonerSerializer wraps all this cumbersome serialization code and hides it to the final user, making it eaiser to use.
